spring:
  application:
    name: audit-lib
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        enable.idempotence: true


audit:
  kafka:
    topic:
      requestsTopic: audit.requests
      methodsTopic: audit.methods
  logging:
    enabled: true
    modes:
      - CONSOLE
      - FILE
      - KAFKA

server:
  port: 8080